### ISSUE TITLE
'Raven' tried to call the protected function 'RavenOverlay7:SetAttribute()

### ISSUE THREAD

**Issue by JohnnyQuest1983** [Dicebar/raven#15] opened 2022-11-06 15:40 UTC
Sometimes referred to by RavenOverlay8, rather than 7.

I'm not sure on what the trigger is, but it appears frequently when entering combat and then very frequently during combat.

```
Message: [ADDON_ACTION_BLOCKED] AddOn 'Raven' tried to call the protected function 'RavenOverlay7:SetAttribute()'.
Time: Sun Nov  6 14:23:54 2022
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Raven' tried to call the protected function 'RavenOverlay7:SetAttribute()'.
[string "@Interface/AddOns/Raven/Nest.lua"]:1215: in function `Nest_DeleteBar'
[string "@Interface/AddOns/Raven/Nest.lua"]:1043: in function `Nest_DeleteBarsWithAttribute'
[string "@Interface/AddOns/Raven/Bars.lua"]:2130: in function `UpdateBars'
[string "@Interface/AddOns/Raven/Main.lua"]:1220: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:897: in function <Interface/AddOns/Raven/Main.lua:893>

Locals: <none>
```

**Comment by voidzone** [comment] 2022-11-06 16:08
```
2x [ADDON_ACTION_BLOCKED] AddOn 'Ace3' tried to call the protected function 'RavenOverlay1:SetAttribute()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Raven/Cancel.lua"]:415: in function `release'
[string "@Interface/AddOns/Raven/Nest.lua"]:1215: in function `Nest_DeleteBar'
[string "@Interface/AddOns/Raven/Nest.lua"]:1043: in function `Nest_DeleteBarsWithAttribute'
[string "@Interface/AddOns/Raven/Bars.lua"]:2130: in function `UpdateBars'
[string "@Interface/AddOns/Raven/Main.lua"]:1220: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:897: in function <Interface/AddOns/Raven/Main.lua:893>

Locals:
Skipped (In Encounter)
```
Believe it's related to Cancel.lua lines 415-416

**Comment by Dicebar** [comment] 2022-11-06 19:13
Is this on live or beta? Do you use combat bars or only normal bars?

**Comment by JohnnyQuest1983** [comment] 2022-11-06 19:18
Live retail. No Raven in-combat bars, just normal bars.

**Comment by voidzone** [comment] 2022-11-06 19:22
Retail, live. Combat bars (buff tracking).

**Comment by Dicebar** [comment] 2022-11-06 19:50
Thanks for the extra info 👍

**Comment by cdgori** [comment] 2022-11-06 20:59
Seeing the same, on live retail:

1x [ADDON_ACTION_BLOCKED] AddOn 'Ace3' tried to call the protected function 'RavenOverlay13:SetAttribute()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Raven/Cancel.lua"]:415: in function `release'
[string "@Interface/AddOns/Raven/Nest.lua"]:1215: in function `Nest_DeleteBar'
[string "@Interface/AddOns/Raven/Nest.lua"]:1043: in function `Nest_DeleteBarsWithAttribute'
[string "@Interface/AddOns/Raven/Bars.lua"]:2130: in function `UpdateBars'
[string "@Interface/AddOns/Raven/Main.lua"]:1220: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:897: in function <Interface/AddOns/Raven/Main.lua:893>

**Comment by Galthariel** [comment] 2022-11-06 23:11
Happens eventually only

`1x [ADDON_ACTION_BLOCKED] AddOn 'Raven' tried to call the protected function 'RavenOverlay7:SetAttribute()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Raven/Cancel.lua"]:415: in function `release'
[string "@Interface/AddOns/Raven/Nest.lua"]:1215: in function `Nest_DeleteBar'
[string "@Interface/AddOns/Raven/Nest.lua"]:1043: in function `Nest_DeleteBarsWithAttribute'
[string "@Interface/AddOns/Raven/Bars.lua"]:2130: in function `UpdateBars'
[string "@Interface/AddOns/Raven/Main.lua"]:1220: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:897: in function <Interface/AddOns/Raven/Main.lua:893>

Locals:
Skipped (In Encounter)`

**Comment by Dicebar** [comment] 2022-11-09 13:52
Hey! This issue has hopefully been fixed in the latest release. I couldn't reproduce the bug locally, but I added a theoretical fix.

If one of you could check that it works as intended, that would be awesome. Thanks!

**Comment by voidzone** [comment] 2022-11-09 15:40
Will test in raid this evening.

**Comment by cdgori** [comment] 2022-11-09 18:32
With the Nov9 version installed I haven't seen the error after doing a bunch of world activity, thank you!

**Comment by Galthariel** [comment] 2022-11-09 20:07
Same here. Good jog Raven Team :-)

**Comment by dorana** [comment] 2022-11-09 21:00
Happy to see it's working for you guys. I'm go ahead and tick this as closed

**Closed by dorana** 2022-11-09 21:00 UTC
Labels: bug, question, live
